version: "3.8"

services:
  postgres:
    image: postgres
    container_name: clo-polibatam-postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-clo-polibatam
    volumes:
      - data_postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: clo-polibatam-redis
    ports:
      - "63791:6379"
    volumes:
      - data_redis:/data

volumes:
  data_postgres:
  data_redis:
